site_name: Advanced Peripherals
site_url: 'https://docs.intelligence-modding.de/'

nav:
    - 'Home': 'index.md'
    - 'Guides':
      - 'NBT Data': 'guides/nbt.md'
      - 'Cooldowns and Fuel consumption': 'guides/cooldowns_and_fuel_consumption.md'
    - 'Peripherals':
      - 'Chat Box': 'peripherals/chat_box.md'
      - 'Energy Detector': 'peripherals/energy_detector.md'
      - 'Environment Detector': 'peripherals/environment_detector.md'
      - 'Player Detector': 'peripherals/player_detector.md'
      - 'Inventory Manager': 'peripherals/inventory_manager.md'
      - 'NBT Storage': 'peripherals/nbt_storage.md'
      - 'Block Reader': 'peripherals/block_reader.md'
      - 'Geo Scanner': 'peripherals/geo_scanner.md'
      - 'Redstone Integrator': 'peripherals/redstone_integrator.md'
      - 'AR Controller': 'peripherals/ar_controller.md'
      - 'ME Bridge': 'peripherals/me_bridge.md'
      - 'RS Bridge': 'peripherals/rs_bridge.md'
      - 'Colony Integrator': 'peripherals/colony_integrator.md'
    - 'Turtles':
      - 'Chatty Turtle': 'turtles/chatty_turtle.md'
      - 'Chunky Turtle': 'turtles/chunky_turtle.md'
      - 'Environment Turtle': 'turtles/environment_turtle.md'
      - 'Player Turtle': 'turtles/player_turtle.md'
      - 'Geoscanning Turtle': 'turtles/geo_scanner_turtle.md'
      - 'Metaphysics':
        - 'Weak Automata': 'turtles/metaphysics/weak_automata.md'
        - 'Husbandry Automata': 'turtles/metaphysics/husbandry_automata.md'
        - 'End Automata': 'turtles/metaphysics/end_automata.md'
        - 'Overpowered Automata': 'turtles/metaphysics/overpowered_automata.md'
    - 'Items':
      - 'AR Goggles': 'items/ar_goggles.md'
      - 'Chunk Controller': 'items/chunk_controller.md'
      - 'Computer Tool': 'items/computer_tool.md'
      - 'Memory Card': 'items/memory_card.md'
      - 'Pocket Computers': 'items/pocket_computer.md'
    - 'Mod Integrations':
      - 'integrations/index.md'
      - 'Minecraft':
        - 'Beacon': 'integrations/minecraft/beacon.md'
        - 'Note Block': 'integrations/minecraft/noteblock.md'
      - 'Botania':
        - 'Flowers': 'integrations/botania/flowers.md'
        - 'Mana Pool': 'integrations/botania/pool.md'
        - 'Mana Spreader': 'integrations/botania/spreader.md'
      - 'Create':
        - 'Basin': 'integrations/create/basin.md'
        - 'Blaze Burner': 'integrations/create/blazeburner.md'
        - 'Fluid Tank': 'integrations/create/fluidtank.md'
        - 'Mechanical Mixer': 'integrations/create/mechanicalmixer.md'
        - 'Blocks with Scroll Behaviour': 'integrations/create/scrollbehaviour.md'
      - 'Draconic Evolution':
        - 'integrations/draconic_evolution/index.md'
        # - 'Energy Core': 'integrations/draconic_evolution/energy_core.md'
        # - 'Reactor': 'integrations/draconic_evolution/reactor.md'
      - 'Immersive Engineering':
        - 'Redstone Wire Connector': 'integrations/immersive_engineering/connector.md'
        - 'Redstone Probe': 'integrations/immersive_engineering/probe.md'
      - 'Integrated Dynamics':
        - 'Variable Store': 'integrations/integrated_dynamics/variable_store.md'
      - 'Mekanism':
        - 'integrations/mekanism/index.md'
        # - 'Boiler Valve': ''
        # - 'Induction Valve': ''
        # - 'Chemical Tank': ''
        # - 'Dynamic Tank': ''
        # - 'Fluid Tank': ''
        # - 'Digital Miner': ''
        # - 'Fission': ''
        # - 'Fusion': ''
        # - 'Solar Evaporation': ''
        # - 'Transmitter': ''
        # - 'Turbine': ''
        # - 'Waste Barrel': ''
        # - 'Energy Blocks': ''
      - 'Storage Drawers':
        - 'Drawer': 'integrations/storage_drawers/drawer.md'
    - 'Changelogs':
      - 'Changelog 0.7r': 'changelogs/0.7r.md'

theme:
    name: material
    custom_dir: overrides
    features:
      - navigation.top
      # - navigation.instant # Breaks 'lightgallery' extension
      - navigation.indexes
      - navigation.tabs
      # - navigation.sections # Makes navigation too long
      - content.code.annotate
      - content.code.copy
    palette:
    - scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search:
      lang: en

extra:
  analytics:
    provider: custom
    property: placeholder

extra_css:
  - extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

repo_url: https://github.com/SirEndii/AdvancedPeripherals
repo_name: SirEndii/AdvancedPeripherals
edit_uri: edit/main/docs/

markdown_extensions:
    - lightgallery
    - mdx_math
    - def_list
    - attr_list
    - md_in_html
    - pymdownx.tasklist:
        custom_checkbox: true
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - admonition
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
