blank_issues_enabled: false
contact_links:
  - name: Mod issues
    url: https://github.com/Seniorendi/AdvancedPeripherals/issues
    about: Please report bugs at the advanced peripherals repository. This repository is for documentation only.
